#!/bin/bash
# REV07: Fri 16 Sep 2022 16:00
# REV06: Sun 23 Feb 2020 15:00
# REV05: Thu  6 Feb 2020 19:00
# REV04: Thu 13 Sep 2018 10:00
# START: Tue 30 Jan 2018 19:00

# Copyright (C) 2018-2022 BinKadal, Sdn. Bhd.
# This program is free script/software. This program is distributed in the hope 
# that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# INFO: Check if the screen size is at least 80 x 23 characters
INFO="../ZADMIN/zzz-generate-READ-THIS-FIRST.sh"
echo "";
[ -f $INFO ] && bash $INFO $0

XX="xx"
echo "RESIZE the screen if this following message does not fit in \"80 x 23\""
echo ""; echo "*** HIT ENTER KEY ***";
[ "$1" = "$XX" ] || (read YY)

cat - << ZCZCNNNN1
(ROW 01) START START START START START START START START START START START START
123456789|123456789|123456789|123456789|123456789|123456789|123456789|123456789|
        10        20        30        40        50        60        70        80
                                                                        (COLUMN)
123456789|123456789|123456789|123456789|123456789|123456789|123456789|123456789|
        10        20        30        40        50        60        70        80
                                                                        (COLUMN)
        10        20        30        40        50        60        70        80
(ROW 09) XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXX                 SCREEN TEST FOR 80 columns x 23 rows                 XXXXX

(ROW 13) XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
123456789|123456789|123456789|123456789|123456789|123456789|123456789|123456789|
        10        20        30        40        50        60        70        80
                                                                        (COLUMN)
        10        20        30        40        50        60        70        80
123456789|123456789|123456789|123456789|123456789|123456789|123456789|123456789|
        10        20        30        40        50        60        70        80
                                                                        (COLUMN)
        10        20        30        40        50        60        70        80
123456789|123456789|123456789|123456789|123456789|123456789|123456789|123456789|
(ROW 23) END END END END END END END END END END END END END END END END END END
ZCZCNNNN1

exit 



