#!/bin/bash
# REV08: Sun 17 Sep 2023 07:00
# REV07: Sun 23 Feb 2020 15:00
# REV06: Thu  6 Feb 2020 20:00
# REV05: Mon 27 Aug 2018 19:00
# START: Mon  4 Sep 2017 16:00

# Copyright (C) 2017-2023 BinKadal, Sdn. Bhd.
# This program is free script/software. This program is distributed in the hope 
# that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# INFO: Does a file exists? Run "bash a04-does-it-exist"
INFO="../ZADMIN/zzz-generate-READ-THIS-FIRST.sh"
echo "";
[ -f $INFO ] && bash $INFO $0

FILE2="ZA-thisfile1.txt"
FILE1="ThisFileDoesNotExist"

echo ""; 
[ -f $FILE1 ] && {
  echo "File: \"$FILE1\" EXISTS!"
}
[ -f $FILE1 ] || {
  echo "File: \"$FILE1\" does not EXISTS!"
}
if [ -f $FILE2 ] ; then
  echo "File: \"$FILE2\" EXISTS!"
else
  echo "File: \"$FILE2\" does not EXISTS!"
fi
exit 0


