#!/bin/bash
# REV08: Sun 17 Sep 2023 07:00
# REV07: Sun 23 Feb 2020 15:00
# REV06: Thu  6 Feb 2020 20:00
# REV05: Mon 27 Aug 2018 20:00
# START: Mon  5 Sep 2016 14:00

# Copyright (C) 2016-2023 BinKadal, Sdn. Bhd.
# This program is free script/software. This program is distributed in the hope 
# that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# INFO: Finding "EXISTS". Just run "bash a05-finding-EXIST"
INFO="../ZADMIN/zzz-generate-READ-THIS-FIRST.sh"
echo "";
[ -f $INFO ] && bash $INFO $0

echo ""; 
echo "File list:"
echo "=========="

for file in `ls a*`
do
   echo -n $file
   if grep -q EXIST $file
      then
      echo -n " YES *******"
   fi
   echo ""
	
done

exit 0

################
# TAKE NOTE (ZA)
# 
# (Line 14)  variable RESULT akan menampung setiap nama file yang ada di 
#            dalam folder W01-demos dengan menggunakan line scripting.
# (Line 20)  mencetak kata File list: dalam tipe string.
# (Line 21)  mencetak suatu simbol dalam tipe string.
# (Line 23)  Jika file tersebut masih terdapat pada folder W01-demos maka 
#            nama file tersebut akan diprint.

