#!/bin/bash
# REV09: Sun 17 Sep 2023 07:00
# REV08: Sun 23 Feb 2020 15:00
# REV07: Thu  6 Feb 2020 20:00
# REV06: Mon 27 Aug 2018 20:00
# START: Mon  5 Sep 2016 14:00

# Copyright (C) 2016-2023 BinKadal, Sdn. Bhd.
# This program is free script/software. This program is distributed in the hope 
# that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# INFO: Just run "bash a06-loop 11 22 33 44"
INFO="../ZADMIN/zzz-generate-READ-THIS-FIRST.sh"
echo ""
[ -f $INFO ] && bash $INFO $0

echo "" 
[ -z "$3" ] && { echo "Run this AGAIN with arguments. Eg. \"bash a06-loop 11 22 33 44\"" ; exit 1; }

echo "========= ========= ========= ========= ========= ========= ========= ========="
echo 'Loop with [*]'
for ii in "$*"
do
   echo $ii
done

echo "========= ========= ========= ========= ========= ========= ========= ========="
echo 'Loop with [@]'
for ii in "$@"
do
   echo $ii
done
exit 0

