#!/bin/bash
# REV08: Sun 17 Sep 2023 08:00
# REV07: Sun 23 Feb 2020 15:00
# REV06: Thu  6 Feb 2020 21:00
# REV05: Mon 27 Aug 2018 20:00
# START: Mon  5 Sep 2016 14:00

# Copyright (C) 2016-2023 BinKadal, Sdn. Bhd.
# This program is free script/software. This program is distributed in the hope 
# that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# INFO: Just run "bash a07-tester"
INFO="../ZADMIN/zzz-generate-READ-THIS-FIRST.sh"
echo "";
[ -f $INFO ] && bash $INFO $0
echo ""; 

for II in ZA-thisfile1.txt ZB-SOURCE NOTHING
do
   echo "================================"
   [ -f $II ] && echo "[$II] is a file"
   [ -f $II ] || echo "[$II] is NOT a file"

   if [ -d $II ] 
      then echo "[$II] is a directory"
   else 
      echo "[$II] is NOT a directory"
   fi
done
echo "================================"

exit

