#!/bin/bash
# REV19: Sun 17 Sep 2023 08:00
# REV10: Sun 23 Feb 2020 15:00
# REV09: Thu  6 Feb 2020 21:00
# REV07: Mon 27 Aug 2018 20:00
# START: Mon  5 Sep 2016 14:00

# Copyright (C) 2016-2023 BinKadal, Sdn. Bhd.
# This program is free script/software. This program is distributed in the hope 
# that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# INFO: Just run "bash a08-append-a-file"
INFO="../ZADMIN/zzz-generate-READ-THIS-FIRST.sh"
echo "";
[ -f $INFO ] && bash $INFO $0

TMPFILE="ZA-thisfile1.txt"
/bin/rm -f $TMPFILE
echo "========= ========= ========= ========= ========= ========= ========= ========="
sleep 1
# ############################################
echo "APPENDING: into $TMPFILE =============="
for ii in f1 f2 
do
   echo "Appending: $ii"
   echo -n "$ii " >> $TMPFILE
done
# ############################################
for ii in f3 f4 f5 f6
do
   echo "Appending: $ii"
   echo "$ii " >> $TMPFILE
done
sleep 1

# #################################################
echo "========= ========= ========= ========= ========= ========= ========= ========="
echo "FILE: $TMPFILE"
cat $TMPFILE

# #################################################
echo "========= ========= ========= ========= ========= ========= ========= ========="
echo "Displaying word by word of $TMPFILE ==="
JJ=0
for ii in `cat $TMPFILE`
do
   JJ=$((JJ + 1))
   echo "Word($JJ): $ii"
done

exit 0


