#!/bin/bash
# REV09: Sun 17 Sep 2023 08:00
# REV08: Fri 16 Sep 2022 16:30
# REV07: Sun 23 Feb 2020 15:00
# REV04: Mon 27 Aug 2018 20:00
# REV02: Fri  8 Sep 2017 21:00
# START: Mon  5 Sep 2016 14:00

# Copyright (C) 2016-2023 BinKadal, Sdn. Bhd.
# This program is free script/software. This program is distributed in the hope 
# that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# INFO: Add line numbers to a file. Run "bash a09-add-numbers ZA-thisfile1.txt"
# INFO:                   The output will be in file ZA-thisfile1.txt.txt"
INFO="../ZADMIN/zzz-generate-READ-THIS-FIRST.sh"
echo "";
[ -f $INFO ] && bash $INFO $0
echo ""; 

[ -f "$1" ] || {
   echo "File $1 does not exist"
   exit -1
}

awk '
BEGIN {
   lll=1
}
{
   printf "%3.3d %s\n", lll++, $0
}' $1 > $1.txt

exit

##################################
# TAKE NOTE (ZA)
#
# Program ini akan menambahkan line numbers pada setiap baris 
# di file tersebut. 
# Jika file yang dicari tidak ada maka akan keluar output 
#        File (file) does not exist 
#
# awk: sebuah perintah pada Linux / Unix yang mempunyai kegunaan untuk 
#      mem-parsing atau mengurai sebuah file.

