#!/bin/bash
# REV07: Sun 17 Sep 2023 08:00
# REV06: Sun 23 Feb 2020 15:00
# REV05: Thu  6 Feb 2020 22:00
# REV04: Mon 27 Aug 2018 20:00
# REV02: Fri  8 Sep 2017 21:00
# START: Thu 18 Aug 2016 19:00

# Copyright (C) 2018-2023 BinKadal, Sdn. Bhd.
# This program is free script/software. This program is distributed in the hope 
# that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# INFO: Just run "bash a10-mysha1"
INFO="../ZADMIN/zzz-generate-READ-THIS-FIRST.sh"
echo "";
[ -f $INFO ] && bash $INFO $0

REGEX='^[0-9]+$'
ONE='1'
TEN='10'
ID=$1

# No argument? Ask student ID
[[ $# =~ $ONE ]] || {
   echo "Enter 10 digits Student ID (NPM)"
   read ID
}

# Is it all digits ?
[[ $ID =~ $REGEX ]] || {
   echo "This is not a number"
   exit 1
}

# Is it a 10 digit ID?
[[ ${#ID} =~ $TEN ]] || {
   echo "Not 10 digits"
   exit 1
}

# Print student ID and its SHA1SUM hash
echo "Student ID (NPM): $ID"
SHA1SUM=`echo "$ID" | sha1sum`
echo "SHA1SUM=$SHA1SUM"
CUT=`echo $SHA1SUM |  cut -c1-10`
echo "CUT=$CUT"
TRANS=`echo $CUT | tr '[a-z]' '[A-Z]'`
echo "TRANS=$TRANS"
echo "Student ID HASH:  0$TRANS"

exit 0

############################
# TAKE NOTE (ZA)
#
# (Line 40)   diminta untuk memasukan NPM atau Student ID
# (Line 41)   SHA-1 (Secure Hash Algorithm) adalah crypthographic has 
#             function yang mengambil input dan menghasilkan 160-bit 
#             (20 byte) sepanjang 40 digit.
# (Line 43)   CUT mengambil hasil SHA1SUM hanya sampai index ke-10 
# (Line 45)   TRANS mengubah char yang menjadi CAPSLOCK atau huruf besar


