#!/bin/bash
# REV06: Sun Feb 23 15:36:04 WIB 2020
# REV05: Thu Feb  6 22:05:52 WIB 2020
# REV04: Mon Aug 27 20:09:03 WIB 2018
# REV02: Fri Sep  8 21:58:19 WIB 2017
# START: Thu Aug 18 19:52:29 WIB 2016

# Copyright (C) 2016-2020 Rahmat M. Samik-Ibrahim 
# http://RahmatM.Samik-Ibrahim.vLSM.org/
# This program is free script/software. This program is distributed in the hope 
# that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# INFO: Just run "bash a10-mysha1"
INFO="../ZADMIN/zzz-generate-READ-THIS-FIRST.sh"
echo "";
[ -f $INFO ] && bash $INFO $0

REGEX='^[0-9]+$'
ONE='1'
TEN='10'
ID=$1

# No argument? Ask student ID
[[ $# =~ $ONE ]] || {
   echo "Enter 10 digits Student ID (NPM)"
   read ID
}

# Is it all digits ?
[[ $ID =~ $REGEX ]] || {
   echo "This is not a number"
   exit 1
}

# Is it a 10 digit ID?
[[ ${#ID} =~ $TEN ]] || {
   echo "Not 10 digits"
   exit 1
}

# Print student ID and its SHA1SUM hash
echo "Student ID (NPM): $ID"
SHA1SUM=`echo "$ID" | sha1sum`
echo "SHA1SUM=$SHA1SUM"
CUT=`echo $SHA1SUM |  cut -c1-10`
echo "CUT=$CUT"
TRANS=`echo $CUT | tr '[a-z]' '[A-Z]'`
echo "TRANS=$TRANS"
echo "Student ID HASH:  0$TRANS"

exit 0

############################
# TAKE NOTE (ZA)
#
# (Line 40)   diminta untuk memasukan NPM atau Student ID
# (Line 41)   SHA-1 (Secure Hash Algorithm) adalah crypthographic has 
#             function yang mengambil input dan menghasilkan 160-bit 
#             (20 byte) sepanjang 40 digit.
# (Line 43)   CUT mengambil hasil SHA1SUM hanya sampai index ke-10 
# (Line 45)   TRANS mengubah char yang menjadi CAPSLOCK atau huruf besar


