#!/bin/bash
# REV20: Fri 16 Sep 2022 17:00
# REV19: Sun 23 Feb 2020 15:00
# REV09: Thu  6 Feb 2020 23:00
# REV07: Mon 27 Aug 2018 20:00
# REV05: Fri  8 Sep 2017 20:00
# START: Thu 19 Dec 2013 00:00

# Copyright (C) 2013-2022 BinKadal, Sdn. Bhd.
# This program is free script/software. This program is distributed in the hope 
# that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# INFO: fixfs: fixing file systems name and mode. Run "bash a12-fixfs"
INFO="../ZADMIN/zzz-generate-READ-THIS-FIRST.sh"
echo "";
[ -f $INFO ] && bash $INFO $0

# Add escape \"
# Replacing all funny and white characters with a dash (-).
# Replacing multiple dashes (---) with a single dash (-)
# No dash before a dot.

function recursive() {
   ls -1 | gawk '{
      FNAME1=$0
      gsub (/"/,"\\\"",FNAME1) 
      FNAME2=FNAME1
      NCHG =  0
      NCHG += gsub (/[\\\*\?\[\]\047":,!( )^@&#]/,"-",FNAME2) 
      NCHG += gsub (/\.-/,"-",FNAME2) 
      NCHG += gsub (/--+/,"-",FNAME2) 
      NCHG += gsub (/_-/,"-",FNAME2) 
      NCHG += gsub (/-_/,"-",FNAME2) 
      NCHG += gsub (/-\./,".",FNAME2) 
      NCHG += gsub (/\._/,"_",FNAME2) 
      NCHG += gsub (/__+/,"_",FNAME2) 
      NCHG += gsub (/_\./,".",FNAME2) 
      NCHG += gsub (/\.\.+/,".",FNAME2) 
      NCHG += gsub (/^-/,"",FNAME2) 
      NCHG += gsub (/-$/,"",FNAME2) 
      if (NCHG > 0) {
         EXTRA=""
         TMPF=FNAME2 EXTRA
         while ((getline < TMPF) >= 0) {
            EXTRA++
            TMPF=FNAME2 "-" EXTRA
         }
         system("/bin/mv -f \""  FNAME1  "\" " TMPF)
      }
   }'

   # chmod 755 for all directories
   # chmod 644 for all files
   for II in {.??,}*
   do
      [ -d "$II" ] && [ ! -L "$II" ] && {
         chmod 755 "$II"
         cd "$II"
         # Recursive inside the DIR
         recursive
         cd ..
      }
      [ -f "$II" ] && chmod 644 "$II"
   done
}

recursive
echo "Check files in subfolder ZB-SOURCE"

exit

###############################
# TAKE NOTE (WK16)
#
# this file will fix name of file that contain irregular name

