#!/bin/bash
# REV04: Sun 17 Sep 2023 08:00
# REV03: Sun 23 Feb 2020 15:00
# REV02: Thu  6 Feb 2020 22:00
# REV01: Wed 12 Sep 2018 20:00
# START: Wed 12 Sep 2018 18:00

# Copyright (C) 2018-2023 BinKadal, Sdn. Bhd.
# This program is free script/software. This program is distributed in the hope 
# that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# INFO: list of all users logged in
INFO="../ZADMIN/zzz-generate-READ-THIS-FIRST.sh"
echo "";
[ -f $INFO ] && bash $INFO $0
echo "========= ========= ========= ========= ========= ========= ========= ========="
cat $0

exit 0

## BASH IGNORES AFTER EXIT

# Execute this following line by line

# AWK ################################# ######

echo "COL1 COL2 COL3" 

echo "COL1 COL2 COL3" | awk '{print $1}'

##############################################

LDIR="ZB-SOURCE"
echo "LDIR=$LDIR"

LAST0="ZB-SOURCE/last.0"
echo "LAST0=$LAST0"

##############################################

checkingdir() {
   [ -d $LDIR ] || {
      echo "mkdir $LDIR"
      mkdir $LDIR
   }
}
  
##############################################

last

last -w

last -w | awk '{print $1}'

last -w | awk '{print $1}' | sort -u 

last -w | awk '{print $1}' | sort -u > $LAST0

##############################################

lastweek() {
   echo ""
   echo "=========================================================================="
   echo "This week visitor(s):"
   echo ""

   COUNTER=0
   for ii in `cat $LAST0`
   do
      printf "%-17s " $ii
      let COUNTER=(COUNTER+1)%4
      if [ $COUNTER -eq 0 ]
      then
         echo ""
         COUNTER=0
      fi
   done
   echo ""
   echo "=========================================================================="
   echo ""
}

