#!/bin/bash
# REV06: Sun 17 Sep 2023 08:00
# REV05: Sun 23 Feb 2020 15:00
# REV04: Thu  6 Feb 2020 22:00
# REV03: Thu 27 Sep 2018 21:00
# START: Wed 12 Sep 2018 20:00

# Copyright (C) 2018-2023 BinKadal, Sdn. Bhd.
# This program is free script/software. This program is distributed in the hope 
# that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# INFO: attendance (absen) list
INFO="../ZADMIN/zzz-generate-READ-THIS-FIRST.sh"
echo "";
[ -f $INFO ] && bash $INFO $0
echo "========= ========= ========= ========= ========= ========= ========= ========="
cat $0

exit 0
## BASH IGNORES AFTER EXIT

w
export PROCPS_USERLEN=16
w
w | gawk '$5 ~ /s$/ {print}'
w | gawk '$5 ~ /s$/ {print $1}'
w | gawk '$5 ~ /s$/ {print $1, systime()}'
w | gawk '$5 ~ /s$/ {print $1, strftime("%y%m%d-%H%M%S", systime())}'
w | gawk '$5 ~ /s$/ {print $1, strftime("%y%m%d-%H%M%S", systime())}' | sort -u


