#!/bin/bash
# REV07: Sun 17 Sep 2023 08:00
# REV06: Sun 23 Feb 2020 15:00
# REV05: Thu  6 Feb 2020 22:00
# REV04: Tue 19 Feb 2019 19:00
# REV01: Thu 30 Mar 2017 17:00
# START: Wed 29 Mar 2017 17:00
#
# Copyright (C) 2017-2023 BinKadal, Sdn. Bhd.
# This program is free script/software. This program is distributed in the hope 
# that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# ===============================================
# cut     remove sections from each line of files
# cut -c  select only these characters
# sha1sum compute and check SHA1 message digest
# tr      translate or delete characters

# INFO: UTS 2017-1 (midterm)
INFO="../ZADMIN/zzz-generate-READ-THIS-FIRST.sh"
echo "";
[ -f $INFO ] && bash $INFO $0

isADigit() {
   [[ $VARIABLE =~ $REGEX ]] || {
      TEXT1="VARIABLE $VARIABLE is not a digit."
      return
   }
   [[ ${#VARIABLE} =~ $TEN ]] && {
      TEXT1="VARIABLE $VARIABLE has 10 digits."
      return
   }
   TEXT1="VARIABLE $VARIABLE has no 10 digits."
}

ONE='1'
TEN='10'
REGEX='^[0-9]+$'
VARIABLE='1234567892'
HASH=`echo "$VARIABLE" | sha1sum`
echo        "$HASH"
isADigit
TEXT2=`echo "$HASH"  | cut -c1-3`
TEXT3=`echo "$TEXT2" | tr '[a-z]' '[A-Z]'`
echo "$TEXT1"
echo "$TEXT2"
echo "$TEXT3"
exit 0

