#!/bin/bash
# REV04: Sun 17 Sep 2023 08:00
# REV03: Sun 23 Feb 2020 15:00
# REV02: Thu  6 Feb 2020 22:00
# REV01: Wed  6 Feb 2019 19:00
# REV00: Thu 17 Jan 2019 11:00
# START: Mon  1 Jan 2018 00:00
# 
# Copyright (C) 2018-2023 BinKadal, Sdn. Bhd.
# This program is free script/software. This program is distributed in the hope 
# that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# INFO: UTS 2018-2 (midterm)
INFO="../ZADMIN/zzz-generate-READ-THIS-FIRST.sh"
echo "";
[ -f $INFO ] && bash $INFO $0

VAR="talas"
echo "$VAR"
KALIMAT="Keladi tidak sama dengan $VAR"
echo "$KALIMAT"
echo "$KALIMAT" | gawk '$5 ~ /s$/ {print $1}'

