#!/bin/bash
# REV04: Sun 17 Sep 2023 08:00
# REV03: Sun 23 Feb 2020 15:00
# REV02: Thu  6 Feb 2020 22:00
# START: Thu 17 Jan 2019 11:00
 
# Copyright (C) 2019-2023 BinKadal, Sdn. Bhd.
# This program is free script/software. This program is distributed in the hope 
# that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# INFO: UTS 2019-1 (midterm)
INFO="../ZADMIN/zzz-generate-READ-THIS-FIRST.sh"
echo "";
[ -f $INFO ] && bash $INFO $0

TIGA=3
ANGKA="1 2 \$TIGA"
echo "START"
echo "ANGKA"
echo "$ANGKA"
echo "$ANGKA" | gawk '/TIGA/ {print $1, $2}'
echo "STOP"

exit 0

