#!/bin/bash
# REV03: Sun Feb 23 15:41:00 WIB 2020
# REV02: Thu Feb  6 22:52:55 WIB 2020
# REV01: Thu Jan 17 11:20:35 WIB 2019
# START: Mon Mar 24 21:00:00
 
# Copyright (C) 2019-2020 Rahmat M. Samik-Ibrahim
# http://RahmatM.Samik-Ibrahim.vLSM.org/
# This program is free script/software. This program is distributed in the hope 
# that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# INFO: UTS 2019-1 (midterm)
INFO="../ZADMIN/zzz-generate-READ-THIS-FIRST.sh"
echo "";
[ -f $INFO ] && bash $INFO $0

TIGA=3
ANGKA="1 2 \$TIGA"
echo "START"
echo "ANGKA"
echo "$ANGKA"
echo "$ANGKA" | gawk '/TIGA/ {print $1, $2}'
echo "STOP"

exit 0

