#!/bin/bash
# REV04: Sun 17 Sep 2023 08:00
# REV03: Sun 23 Feb 2020 15:00
# REV02: Thu  6 Feb 2020 22:00
# REV01: Thu  6 Feb 2020 17:00
# START: Fri 25 Oct 2019 13:00

# Copyright (C) 2019-2023 BinKadal, Sdn. Bhd.
# This free document is distributed in the hope that it will be 
# useful, but WITHOUT ANY WARRANTY; without even the implied 
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# INFO: UTS 2019-2 (midterm)
INFO="../ZADMIN/zzz-generate-READ-THIS-FIRST.sh"
echo "";
[ -f $INFO ] && bash $INFO $0

LINE1="= BEGIN"
LINE2="TESTING regex using awk"
LINE3="TESTING REGEX using awk"
LINE4="= = END"

echo $LINE1
echo $LINE2 | awk '/regex/{print $1}' 
echo $LINE3 | awk '/regex/{print $1}' 
echo $LINE2 | tr [A-Z] [a-z] | awk '/regex/{print $1}' 
echo $LINE3 | tr [A-Z] [a-z] | awk '/regex/{print $1}' 
echo $LINE4

exit 0


