# REV08 Mon Dec  9 16:57:42 WIB 2019
# REV07 Tue Apr  2 09:40:27 WIB 2019
# REV06 Mon Feb 11 15:27:05 WIB 2019
# REV04 Wed Nov  1 13:30:30 WIB 2017
# START Mon Oct 24 09:18:34 WIB 2016
# DEMOFILES=\
# 	demo-file1.txt \
# 	demo-file2.txt \

CC='gcc'
CFLAGS='-std=c99'
 
P00=00-show-pid
P01=01-fork
P02=02-fork
P03=03-fork
P04=04-sleep
P05a=05a-fork
P05b=05b-fork
P06a=06a-fork
P06b=06b-fork
P06c=06c-fork
P06d=06d-fork
P07=07-execlp
P08=08-fork
P09=09-fork
P10=10-fork
P11=11-fork
P12=12-fork
P13=13-uas161
P14=14-uas162
P15=15-uas171
P16=16-uas172


EXECS= \
	$(P00)  \
	$(P01)  \
	$(P02)  \
	$(P03)  \
	$(P04)  \
	$(P05a) \
	$(P05b) \
	$(P06a) \
	$(P06b) \
	$(P06c) \
	$(P06d) \
	$(P07)  \
	$(P08)  \
	$(P09)  \
	$(P10)  \
	$(P11)  \
	$(P12)  \
	$(P13)  \
	$(P14)  \
	$(P15)  \
	$(P16)  \


all:	$(EXECS)

clean:
	rm -f $(EXECS)

