# (c) 2016-2021 Rahmat M. Samik-Ibrahim
# REV04 Fri  2 Apr 07:12:47 WIB 2021
# REV03 Fri  7 Feb 00:03:32 WIB 2020
# REV02 Fri 25 Jan 18:57:28 WIB 2019
# REV01 Tue 22 Aug 14:45:14 WIB 2017
# START Fri 01 Jan 00:00:00 WIB 2016
# This is a free Makefile configuration.

# INFO: With this "Makefile", just run:
# INFO:                     make

ALL:	c-program-example

c-program-example: c-program-example.c
	gcc -std=gnu99 -o c-program-example c-program-example.c

.phony: ALL clean

clean:
	rm -f c-program-example

